#!/bin/bash  
echo -e "The Potatoes Project - Cooking the potatoe..."
#echo -e "Compiling the project..." 
#antlr4-build -v
#echo "Processing ./PotatoesMain.java"
#javac "PotatoesMain.java"
#echo -e "Done!\n"

if [ ! -f ./PotatoesMain.class ]; then
	echo -e "Please build the project - by running ./build - before compiling a file."
	exit 1
fi

java PotatoesMain $1
exit 0
