#!/bin/bash  
echo -e "LFA Project 28 June 2018\nInes Justo (84804), Luis Pedro Moura (83808), Maria Joao Lavoura (84681), Pedro Teixeira (84715)\n"
echo -e "Compiling the project..." 
#antlr4-build -v
echo "Processing ./PotatoesMain.java"
javac "PotatoesMain.java"
echo -e "Done!\n"
java PotatoesMain $1
