#!/bin/bash  
echo -e "Pedro Teixeira June 22, 2018\n"

case "$1" in
  "-t"  | "-test") 
	antlr4-test typesGrammar.Types typesFile -tokens < tests/typesGrammar/$2  && antlr4-test typesGrammar.Types typesFile -gui < tests/typesGrammar/$2;;
  "-r"  | "-run")  
	java TestTypesFileInfo tests/typesGrammar/$2;;
  "-b"  | "-build") 
	antlr4-build -v ;;
	#javac -cp ".:/mnt/c/Users/Pedro/Desktop/LFA_Project/LFA_Project/src/utils/jung2-2_0_1/collections-generic-4.01.jar:/mnt/c/Users/Pedro/Desktop/LFA_Project/LFA_Project/src/utils/jung2-2_0_1/jung-api-2.0.1.jar:/mnt/c/Users/Pedro/Desktop/LFA_Project/LFA_Project/src/utils/jung2-2_0_1/jung-graph-impl-2.0.1.jar" */*.java;;
	
	
  "-c"  | "-clean") 
	antlr4-clean;;
  *) 
	echo -e "Usage: test [option] <test file> 
  \nAvailable options:
  -> test -t  <file>   : Test the file - shows tokens & Parse Tree (ANTLR Test). 
  -> test -r  <file>   : Run the file (Types File Interpreter).
  -> test -b           : Build the project.
  -> test -c           : Clean the project.
  " ;;
esac
